spring.application.name=journalApp

spring.data.mongodb.host=cluster0.qfdiksu.mongodb.net
spring.data.mongodb.port=27017
spring.data.mongodb.username=surya
spring.data.mongodb.password=surya@2004
spring.data.mongodb.database=journaldb
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true